name: Web Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # download repo
    - uses: actions/checkout@v4
    
    # setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2
      
    # setup chromedriver
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: 'latest'
    
    # setup gradle 
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    # build first (without tests)
    - name: Build project
      run: ./gradlew build -x test
    
    # run tests with headless chrome
    - name: Run tests
      run: ./gradlew test --continue
      continue-on-error: true
      env:
        CHROME_BIN: /usr/bin/google-chrome
        DISPLAY: :99.0
        CHROME_OPTIONS: --headless --no-sandbox --disable-dev-shm-usage --disable-gpu
    
    # upload test results
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          build/test-results/
          build/reports/
